title: Ching-An(Ann) Chung # your name (or website title) here
logo: "/images/IMG_2124 (2).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)   
  <p align="center">
  <a href="https://chriskhanhtran.github.io/pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  </p>
  
  <p align="justify">
  Summary
  <br><br>
  SKILLS
  <br><br>
  </p>

theme: jekyll-theme-minimal
