title: Ching-An(Ann) Chung # your name (or website title) here
logo: "/images/IMG_2124.JPG" # your photo (or logo) here
<br><br>
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <br><br>
  First description 
  <br><br>
  Second description 
  <br><br>
  <br><br>
  <a href="www.linkedin.com/in/ching-an-chung">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
